OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "uKAcWnrmqyOFdqNd625a799a054843638fC10596BaA014E4"

GLMModel:
  model_url: "https://api.xiaoai.plus/v1"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"